FROM node:22.13 AS angular-builder

WORKDIR /app

COPY . .

RUN npm install --silent --force
RUN npm install -g @angular/cli
RUN ng build --configuration production

FROM nginx:alpine

COPY --from=angular-builder /app/dist/eenvo/browser /usr/share/nginx/html

COPY --from=angular-builder /app/.well-known /usr/share/nginx/html/.well-known

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

COPY entrypoint-web.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]