FROM node:22.13 AS angular-builder

WORKDIR /app

COPY . .

ARG DEVEXTREME_KEY
ENV DEVEXTREME_KEY=$DEVEXTREME_KEY

RUN npm install --silent --force
RUN npm install -g @angular/cli
RUN ng build --configuration production

FROM nginx:alpine

COPY --from=angular-builder /app/dist/eenvo/browser /usr/share/nginx/html

COPY --from=angular-builder /app/.well-known /usr/share/nginx/html/.well-known

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY replace-env.sh /replace-env.sh

RUN chmod +x /replace-env.sh

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]