version: '3.8'

services:
  eenvo-web:
    image: ivucicev/eenvo-web:latest
    environment:
      DEVEXTREME_KEY: ${DEVEXTREME_KEY}
      API_URL: http://localhost:8090
    ports:
      - "80:80"

  eenvo-api:
    image: ivucicev/eenvo-api:latest
    volumes:
      - ./pb_data:/pb/pb_data
    ports:
      - "8090:8090"
    environment:
      POCKETBASE_ADMIN_EMAIL: ${POCKETBASE_ADMIN_EMAIL}
      POCKETBASE_ADMIN_PASS: ${POCKETBASE_ADMIN_PASS}