name: Build

on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Bump package.json version
        run: |
            git config --local user.name "github-actions"
            git config --local user.email "github-actions@github.com"
            VER=$(npm version patch)
            echo "Bumped version to $VER"
            git add . || "Nothing changed"
            # Commit only if there are changes
            if git diff --cached --quiet; then
                echo "No changes to commit."
            else
                git commit -m "Version bump to $VER"
                echo "Committed version bump"
            fi
      
      - name: Push changes
        env:
            GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ivucicev/eenvo.io

      - name: Build and push Docker image
        env:
            DEVEXTREME_KEY: ${{ secrets.DEVEX }}
        if: contains(github.event.head_commit.message, 'ci')
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile
          push: true
          build-args: |
            DEVEXTREME_KEY=${{ secrets.DEVEX }}
          tags: |
            ivucicev/eenvo.io:latest
            ivucicev/eenvo.io:${{ github.run_id }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Web App Docker image
        if: contains(github.event.head_commit.message, 'ci')
        id: push-webapp
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile.web
          push: true
          tags: |
            ivucicev/eenvo-web:latest
            ivucicev/eenvo-web:${{ github.run_id }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Web API Docker image
        if: contains(github.event.head_commit.message, 'ci')
        id: push-webapi
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./dockerfile.api
          push: true
          tags: |
            ivucicev/eenvo-api:latest
            ivucicev/eenvo-api:${{ github.run_id }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: Run script on DigitalOcean server
        if: contains(github.event.head_commit.message, 'release')
        uses: appleboy/ssh-action@v0.1.0
        with:
            host: ${{ secrets.DIGITALOCEAN_HOST }}
            username: ${{ secrets.DIGITALOCEAN_USERNAME }}
            key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
            script: |
                #!/bin/bash
                # Your script commands here
                echo "Running script on DigitalOcean server"
                ./pullAndRun.sh